name: Build React Router App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React Router App
        run: npm run build

      - name: Debug: Check build output
        run: |
          echo "Listing build/server directory:"
          ls -la build/server

      - name: Upload build artifacts (server build)
        uses: actions/upload-artifact@v4
        with:
          name: react-router-build
          path: build/server/
